name: CI Placeholder

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  lint:
    name: Placeholder — Lint
    runs-on: ubuntu-latest
    steps:
      - name: TODO lint in Phase 4
        run: echo "Phase 4: add pnpm check"

  typecheck:
    name: Placeholder — Typecheck
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: TODO typecheck in Phase 4
        run: echo "Phase 4: add pnpm typecheck"

  test:
    name: Placeholder — Test
    runs-on: ubuntu-latest
    needs: typecheck
    steps:
      - name: TODO test in Phase 4
        run: echo "Phase 4: add pnpm test suite"

  build:
    name: Placeholder — Build
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: TODO build in Phase 4
        run: echo "Phase 4: add pnpm build"
